#!/bin/bash

# Script to update bottle SHA256 hashes in the formula
# Usage: ./update-bottles.sh <release-tag>

set -e

RELEASE_TAG=${1:-v1.4}
FORMULA_FILE="Formula/ocesql@1.4.rb"

if [ ! -f "$FORMULA_FILE" ]; then
    echo "Error: Formula file not found: $FORMULA_FILE"
    exit 1
fi

echo "Updating bottle SHA256 hashes for release: $RELEASE_TAG"

# Function to get SHA256 from GitHub release
get_sha256() {
    local filename=$1
    local url="https://github.com/dirkey/homebrew-ocesql/releases/download/$RELEASE_TAG/$filename"
    
    echo "Fetching $url..."
    local sha256=$(curl -sL "$url" | shasum -a 256 | cut -d' ' -f1)
    echo "$sha256"
}

# Define bottle filenames (these will be generated by the GitHub workflow)
ARM64_SONOMA_FILE="ocesql@1.4--1.4.arm64_sonoma.bottle.tar.gz"
ARM64_VENTURA_FILE="ocesql@1.4--1.4.arm64_ventura.bottle.tar.gz"
MONTEREY_FILE="ocesql@1.4--1.4.monterey.bottle.tar.gz"
X86_64_LINUX_FILE="ocesql@1.4--1.4.x86_64_linux.bottle.tar.gz"

echo "Getting SHA256 hashes..."

# Get SHA256 hashes (only if files exist in release)
if curl -sI "https://github.com/dirkey/homebrew-ocesql/releases/download/$RELEASE_TAG/$ARM64_SONOMA_FILE" | grep -q "200 OK"; then
    ARM64_SONOMA_SHA=$(get_sha256 "$ARM64_SONOMA_FILE")
    sed -i.bak "s/sha256_placeholder_arm64_sonoma/$ARM64_SONOMA_SHA/" "$FORMULA_FILE"
fi

if curl -sI "https://github.com/dirkey/homebrew-ocesql/releases/download/$RELEASE_TAG/$ARM64_VENTURA_FILE" | grep -q "200 OK"; then
    ARM64_VENTURA_SHA=$(get_sha256 "$ARM64_VENTURA_FILE")
    sed -i.bak "s/sha256_placeholder_arm64_ventura/$ARM64_VENTURA_SHA/" "$FORMULA_FILE"
fi

if curl -sI "https://github.com/dirkey/homebrew-ocesql/releases/download/$RELEASE_TAG/$MONTEREY_FILE" | grep -q "200 OK"; then
    MONTEREY_SHA=$(get_sha256 "$MONTEREY_FILE")
    sed -i.bak "s/sha256_placeholder_monterey/$MONTEREY_SHA/" "$FORMULA_FILE"
fi

if curl -sI "https://github.com/dirkey/homebrew-ocesql/releases/download/$RELEASE_TAG/$X86_64_LINUX_FILE" | grep -q "200 OK"; then
    X86_64_LINUX_SHA=$(get_sha256 "$X86_64_LINUX_FILE")
    sed -i.bak "s/sha256_placeholder_x86_64_linux/$X86_64_LINUX_SHA/" "$FORMULA_FILE"
fi

# Remove backup file
rm -f "$FORMULA_FILE.bak"

echo "✅ Bottle SHA256 hashes updated successfully!"
echo "🚀 Don't forget to commit and push the changes."
